create table disc_option (
   id                   int                  not null,
   name                 nvarchar(200)        null,
   remark               nvarchar(800)        null,
   custtype_id_list     varchar(250)         null,
   include_shop         varchar(250)         null,
   include_shop_group   varchar(250)         null,
   exclude_shop         varchar(250)         null,
   start_date           datetime             null,
   end_date             datetime             null,
   start_time           char(5)              null,
   end_time             char(5)              null,
   mon                  bit                  null,
   tue                  bit                  null,
   web                  bit                  null,
   thu                  bit                  null,
   fri                  bit                  null,
   sat                  bit                  null,
   sun                  bit                  null,
   every_day_of_month   varchar(250)         null,
   include_date         varchar(250)         null,
   exclude_date         varchar(250)         null,
   last_day_of_month_allow bit                  null,
   -----Finished
   type1                varchar(20)          null,
   type_include_list1   varchar(250)         null,
   type_exclude_list1   varchar(250)         null,
   type2                varchar(20)          null,
   type_include_list2   varchar(250)         null,
   type_exclude_list2   varchar(250)         null,
   type3                varchar(20)          null,
   type_include_list3   varchar(250)         null,
   type_exclude_list3   varchar(250)         null,
   type4                varchar(20)          null,
   type_include_list4   varchar(250)         null,
   type_exclude_list4   varchar(250)         null,
   type5                varchar(20)          null,
   type_include_list5   varchar(250)         null,
   type_exclude_list5   varchar(250)         null,
   updateno             int                  null,
   suspend              bit                  null,
   active               bit                  null,
   create_by            int                  null,
   create_date          datetime             null,
   create_station_id    int                  null,
   edit_by              int                  null,
   edit_date            datetime             null,
   edit_station_id      int                  null,
   void_by              int                  null,
   void_date            datetime             null,
   void_station_id      int                  null,
   constraint PK_DISC_OPTION primary key (id)
)

